# Generated by Django 4.0.3 on 2022-04-14 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('middle_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('nick_name', models.CharField(default='', max_length=255)),
                ('date_of_birth', models.CharField(default='', max_length=255)),
                ('place_of_birth', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('marital_status', models.CharField(default='', max_length=255)),
                ('blood_group', models.CharField(default='', max_length=255)),
                ('religion', models.CharField(default='', max_length=255)),
                ('nationality', models.CharField(default='', max_length=255)),
                ('national_id', models.CharField(default='', max_length=255)),
                ('passport_no', models.CharField(default='', max_length=255)),
                ('social_network_id', models.CharField(default='', max_length=255)),
                ('im', models.CharField(default='', max_length=255)),
                ('about_you', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=255)),
                ('present_mobile', models.CharField(default='', max_length=255)),
                ('permanent_mobile', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('alternative_email', models.CharField(default='', max_length=255)),
                ('father_name', models.CharField(default='', max_length=255)),
                ('father_contact_no', models.CharField(default='', max_length=255)),
                ('father_occupation', models.CharField(default='', max_length=255)),
                ('father_designation', models.CharField(default='', max_length=255)),
                ('father_employers_name', models.CharField(default='', max_length=255)),
                ('father_eannual_income', models.CharField(default='', max_length=255)),
                ('mother_name', models.CharField(default='', max_length=255)),
                ('mother_contact_no', models.CharField(default='', max_length=255)),
                ('mother_occupation', models.CharField(default='', max_length=255)),
                ('mother_designation', models.CharField(default='', max_length=255)),
                ('mother_employer_name', models.CharField(default='', max_length=255)),
                ('mother_annual_income', models.CharField(default='', max_length=255)),
                ('parents_address', models.CharField(default='', max_length=255)),
                ('local_guardian_name', models.CharField(default='', max_length=255)),
                ('local_guardian_contact_no', models.CharField(default='', max_length=255)),
                ('relation_with_local_guardian', models.CharField(default='', max_length=255)),
                ('local_guardian_address', models.CharField(default='', max_length=255)),
                ('present_address', models.CharField(default='', max_length=255)),
                ('present_address_post_office', models.CharField(default='', max_length=255)),
                ('present_address_police_station', models.CharField(default='', max_length=255)),
                ('present_address_district', models.CharField(default='', max_length=255)),
                ('present_address_division', models.CharField(default='', max_length=255)),
                ('present_address_country', models.CharField(default='', max_length=255)),
                ('present_address_zipcode', models.CharField(default='', max_length=255)),
                ('permanent_address', models.CharField(default='', max_length=255)),
                ('permanent_address_post_office', models.CharField(default='', max_length=255)),
                ('permanent_address_police_station', models.CharField(default='', max_length=255)),
                ('permanent_address_district', models.CharField(default='', max_length=255)),
                ('permanent_address_division', models.CharField(default='', max_length=255)),
                ('permanent_address_country', models.CharField(default='', max_length=255)),
                ('permanent_address_zipcode', models.CharField(default='', max_length=255)),
                ('hostel_address', models.CharField(default='', max_length=255)),
                ('mess_address', models.CharField(default='', max_length=255)),
                ('other_address', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
