# Generated by Django 4.0.3 on 2022-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profileinfo_about_you_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='photo',
            field=models.ImageField(default='photo/default.png', upload_to='photo'),
        ),
    ]
