# Generated by Django 4.0.3 on 2022-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_alter_result_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cgpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=255)),
                ('semestername', models.CharField(default='', max_length=255)),
                ('total_credit', models.IntegerField()),
                ('sgpa', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
