# Generated by Django 4.0.3 on 2022-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='dept',
            field=models.CharField(default='', max_length=255),
        ),
    ]
