# Generated by Django 4.0.3 on 2022-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0012_profileinfo_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='batch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='enrollment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
