# Generated by Django 4.0.3 on 2022-04-14 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0013_profileinfo_batch_profileinfo_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payable', models.CharField(default='', max_length=255)),
                ('total_paid', models.CharField(default='', max_length=255)),
                ('total_due', models.CharField(default='', max_length=255)),
                ('total_others', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
