# Generated by Django 4.0.3 on 2022-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0015_sgpadashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgpadashboard',
            name='fall_19',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sgpadashboard',
            name='fall_21',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sgpadashboard',
            name='spring_22',
            field=models.FloatField(),
        ),
    ]
